name: Bug Report
description: Report a reproducible bug or regression in this library.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report

        Thanks for taking the time to report a bug!

        Please fill out the following carefully before opening a new issue.
        **Issues missing required information may be closed without investigation.**

  - type: checkboxes
    attributes:
      label: Before submitting a new issue
      options:
        - label: I tested using the **latest version** of the library.
          required: true
        - label: I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of React Native.
          required: true
        - label: I checked for [existing issues](https://github.com/lodev09/react-native-true-sheet/issues) that might answer my question.
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Provide a clear and concise description of what the bug is.
      placeholder: When I do X, I expect Y to happen, but Z happens instead.
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Affected Platforms
      options:
        - label: iOS
        - label: Android
        - label: Web
        - label: Other

  - type: input
    id: library-version
    attributes:
      label: Library Version
      description: What version of @lodev09/react-native-true-sheet are you using?
      placeholder: "x.x.x"
    validations:
      required: true

  - type: textarea
    id: react-native-info
    attributes:
      label: Environment Info
      description: Run `npx react-native info` in your terminal and paste the results here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a clear list of steps to reproduce the problem.
      placeholder: |
        1. Open the app
        2. Navigate to...
        3. Tap on...
        4. See error
    validations:
      required: true

  - type: input
    id: reproducible-example
    attributes:
      label: Repro
      description: A link to a GitHub repository, Expo Snack, CodeSandbox, or StackBlitz.
      placeholder: https://github.com/username/repo
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or screen recordings about the problem here.
